### ISSUE TITLE
Memory Overflow Issue During SNAF Execution

### ISSUE THREAD

**Issue by yiolino** [frankligy/SNAF#27]
Firstly, thank you for the development of the SNAF software!  
I am encountering a memory overflow issue when running SNAF with 150bp paired-end FASTQ files.   

## Environment:
OS: Ubuntu 20.04
RAM: 256GB

## Steps to Reproduce and Observed Behavior:
1. Trimming of FASTQ files.
2. Running STAR PASS1.
3. Creating STAR 2nd index.
4. Executing STAR PASS2.
5. Using AltAnalyze.
6. Running SNAF.

During the SNAF run, a memory overflow occurs.   
I suspect this is due to the large number of lines (over 30,000) in the `counts.original.pruned.txt` file generated by AltAnalyze.

## Temporary Solution:
I modified the snaf.initialize method parameters (setting `t_min` to 100), which allowed the execution to complete.   
However, I am uncertain if this is the optimal parameter setting.

## Question:
Is there a recommended or more optimal way to avoid memory overflow issues when running SNAF with large input files?

**Comment by frankligy** [comment]
Hi @yiolino,

Thanks for bringing this up, increasing `t_min` certainly can reduce the number of junctions deemed tumor-specific (more stringent), which is a valid way to work this around. But it indeed sounds strange to me, as I recall I tested files even bigger than `30,000` rows.

Let me run a diagnosis tomorrow on my end using a big file, and I'll keep you updated on the progress!

Best,
Frank

**Comment by frankligy** [comment]
Hi @yiolino,

Sorry I got caught up with work today and hasn't get a chance to run a test, but based on what you showed, 411 valid NeoJunction should definitely work without too much memory footprint. Could I ask are you using `netMHCpan` or `MHCflurry`?

Internally, I pretty switch to `netMHCpan` all the time, just because it's faster and seems to be integrated very well, even for over 100-150k junctions. If you are not using `netMHCpan`, would you like to give it a try?

In the meantime, let me try to find a time to systematic track the memory footprint this weekend.

Best,
Frank

**Comment by yiolino** [comment]
Hi @frankligy,

Thank you for your response.
Please don't worry about the delay; I understand that work can get busy.

To answer your question, we have been using MHCflurry in our pipeline.
However, based on your suggestion, we are open to trying netMHCpan to see if it improves our results and reduces the memory footprint.

Thanks again for your support and assistance.

Best regards,
yiolino

**Comment by frankligy** [comment]
Hi @yiolino,

I did the test on my end, using the example file I included in the `test` folder:

```
2024-02-03 14:18:57 starting initialization
Current loaded gtex cohort with shape (12827, 2629)
Adding cohort tcga_control with shape (12902, 705) to the database
now the shape of control db is (12908, 3334)
Adding cohort gtex_skin with shape (12098, 313) to the database
now the shape of control db is (12908, 3647)
2024-02-03 14:19:51 finishing initialization
reduce valid NeoJunction from 12927 to 840 because they are present in GTEx
reduce valid Neojunction from 840 to 668 because they are present in added control tcga_control
reduce valid Neojunction from 668 to 597 because they are present in added control gtex_skin
junction_count_matrix: (12927, 2)
cores: 8
valid: 597
invalid: 12330
cond_df: (12927, 2)
subset: (597, 2)
translated: list of 597 nj objects
cond_subset_df: (597, 2)
results: list of length None
100%|███████████████████████████████████████████| 75/75 [01:57<00:00,  1.56s/it]
100%|███████████████████████████████████████████| 75/75 [01:57<00:00,  1.56s/it]
100%|███████████████████████████████████████████| 75/75 [02:04<00:00,  1.65s/it]
100%|███████████████████████████████████████████| 74/74 [02:08<00:00,  1.74s/it]
100%|███████████████████████████████████████████| 75/75 [02:12<00:00,  1.76s/it]
100%|███████████████████████████████████████████| 74/74 [02:19<00:00,  1.88s/it]
100%|███████████████████████████████████████████| 74/74 [02:22<00:00,  1.92s/it]
100%|███████████████████████████████████████████| 75/75 [02:32<00:00,  2.04s/it]
```

First, The parent process memory usage is like below with the maximum 12G:

```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    10    377.5 MiB    377.5 MiB           1   @profile
    11                                         def run():
    12                                             # change the below two paths
    13    377.5 MiB      0.0 MiB           1       db_dir = '/gpfs/data/yarmarkovichlab/Frank/SNAF_ecosystem/data'
    14    377.5 MiB      0.0 MiB           1       netMHCpan_path = '/gpfs/data/yarmarkovichlab/Frank/SNAF_ecosystem/netMHCpan-4.1/netMHCpan' 
    15                                         
    16                                             # initiate
    17   2763.3 MiB   2385.8 MiB           1       tcga_ctrl_db = ad.read_h5ad(os.path.join(db_dir,'controls','tcga_matched_control_junction_count.h5ad'))
    18   3519.2 MiB    755.9 MiB           1       gtex_skin_ctrl_db = ad.read_h5ad(os.path.join(db_dir,'controls','gtex_skin_count.h5ad'))
    19   3519.2 MiB      0.0 MiB           1       add_control = {'tcga_control':tcga_ctrl_db,'gtex_skin':gtex_skin_ctrl_db}
    20   3520.6 MiB      1.4 MiB           1       df = pd.read_csv('counts.original.pruned.txt',sep='\t',index_col=0)
    21  12991.7 MiB   9471.1 MiB           1       snaf.initialize(df=df,db_dir=db_dir,binding_method='netMHCpan',software_path=netMHCpan_path,add_control=add_control)
    22                                         
    23                                             # test T antigen function
    24  12993.5 MiB      1.8 MiB           1       jcmq = snaf.JunctionCountMatrixQuery(junction_count_matrix=df,cores=8,add_control=add_control,outdir='result')
    25  12993.5 MiB      0.0 MiB           1       hlas = [['HLA-A*02:01','HLA-A*02:01','HLA-B*39:10','HLA-B*15:01','HLA-C*03:03','HLA-C*12:03'],
    26  12993.5 MiB      0.0 MiB           1               ['HLA-A*02:01','HLA-A*01:01','HLA-B*40:01','HLA-B*52:01','HLA-C*03:04','HLA-C*12:02']]
    27  12781.9 MiB   -211.6 MiB           1       jcmq.run(hlas=hlas,outdir='./result')
    28  12833.2 MiB     51.3 MiB           1       snaf.JunctionCountMatrixQuery.generate_results(path='./result/after_prediction.p',outdir='./result')
```

It can also be plotted as below:

<img width="1308" alt="Screenshot 2024-02-03 at 3 06 32 PM" src="https://github.com/frankligy/SNAF/assets/59619831/88619e0e-8cfb-4424-a998-473218e05872">

Since SNAF program automatically use multiple cores in two stages, one is when spawning MHC binding and immunogenicity prediction, and speed up result generation by utilizing multiple cores in the nodes (using the # of cores you specified). We can also track the all the child process as well:

 
<img width="1199" alt="Screenshot 2024-02-03 at 3 09 52 PM" src="https://github.com/frankligy/SNAF/assets/59619831/1bf7105f-7db6-4de7-aba3-10a8cbae37d4">

Or aggregating all child process memory usage all together:

<img width="1329" alt="Screenshot 2024-02-03 at 3 10 27 PM" src="https://github.com/frankligy/SNAF/assets/59619831/82a0063f-ee3a-4f72-bb84-10ce70e51be0">

So I guess, in conclusion, by using `netMHCpan` and multiple cores, the memory usage should not exceed 25-50G, and from my experience for over 20K Neojunctions (after filter, before filter will be like 150K junctions), 200GB should be sufficient.

Let me know if switching to `netMHCpan` helps reduce the memory usage on your end a bit!

Best,
Frank

**Comment by yiolino** [comment]
Hi @frankligy ,

Thank you so much for conducting the detailed test and sharing the results with me. It's very informative to see how netMHCpan can potentially help in reducing memory usage.

We will set up our environment to switch to netMHCpan and give it a try. 
Once we have run our tests and observed the outcomes, I will report back to you with our findings.

I appreciate your assistance and the time you've invested in helping us address this issue.

Best regards,
yiolino

**Comment by yiolino** [comment]
Hi @frankligy 

I wanted to update you on our progress. 
We conducted a test in our environment using netMHCpan, and I am pleased to report that it was a success. 
By switching to netMHCpan, we were able to complete the analysis with the default parameters, and importantly, we did not encounter any memory overflow issues.

Thank you once again for all your support.

Best regards,
yiolino
